process.env.NODE_ENV = process.env.NODE_ENV || 'development';

import { ValidationPipe, VersioningType } from '@nestjs/common';
import { ConfigType } from '@nestjs/config';
import { IEntryNestModule, NestFactory } from '@nestjs/core';
import { DocumentBuilder, SwaggerModule } from '@nestjs/swagger';

import { appConfigFactory } from './app-config.factory';
import { AppModule } from './app.module';
import { AppType } from './enums';
// eslint-disable-next-line @typescript-eslint/ban-ts-comment -- The generated module is absent when type checking starts.
// @ts-ignore -- Generated by the Nest Swagger plugin during this build.
import metadata from './metadata';
import { timConfigFactory } from './tim/tim-config.factory';
import { TIM_COOKIE_AUTH_SECURITY_NAME } from './tim/tim.constants';

type AppBootstrapConfig = {
  readonly appType: AppType;
  readonly module: IEntryNestModule;
  readonly port: (config: ConfigType<typeof appConfigFactory>) => number;
};

const appBootstrapConfigs = [
  {
    appType: AppType.Public,
    module: AppModule.register(AppType.Public),
    port: (config) => config.publicPort ?? 3000,
  },
  {
    appType: AppType.Private,
    module: AppModule.register(AppType.Private),
    port: (config) => config.privatePort ?? 3001,
  },
] satisfies AppBootstrapConfig[];

async function bootstrap() {
  await Promise.all(appBootstrapConfigs.map(bootstrapApp));
}

const bootstrapApp = async ({ appType, module, port }: AppBootstrapConfig) => {
  const app = await NestFactory.create(module);

  const apiConfig = app.get<ConfigType<typeof appConfigFactory>>(appConfigFactory.KEY);
  const timConfig = app.get<ConfigType<typeof timConfigFactory>>(timConfigFactory.KEY);

  if (apiConfig.corsOrigin) {
    app.enableCors({ origin: apiConfig.corsOrigin });
  }

  app.useGlobalPipes(new ValidationPipe({ transform: true, whitelist: true }));
  app.enableVersioning({ type: VersioningType.URI });
  app.enableShutdownHooks();

  app.setGlobalPrefix(appType, {
    exclude: ['health'],
  });

  if (apiConfig.documentationEnabled) {
    const config = new DocumentBuilder()
      .addCookieAuth(
        timConfig.jwtCookieNames[0],
        { type: 'apiKey', description: 'JWT Cookie' },
        TIM_COOKIE_AUTH_SECURITY_NAME,
      )
      .setTitle(`API Documentation (${appType})`)
      .setVersion('1.0.0')
      .build();
    await SwaggerModule.loadPluginMetadata(metadata);
    const document = SwaggerModule.createDocument(app, config);
    SwaggerModule.setup('documentation', app, document, {
      swaggerOptions: {
        operationsSorter: 'alpha',
        persistAuthorization: true,
        tagsSorter: 'alpha',
        withCredentials: true,
      },
    });
  }

  await app.listen(port(apiConfig));
};

bootstrap();
