process.env.NODE_ENV = process.env.NODE_ENV || 'development';

import { ValidationPipe, VersioningType } from '@nestjs/common';
import { ConfigType } from '@nestjs/config';
import { NestFactory } from '@nestjs/core';
import { DocumentBuilder, SwaggerModule } from '@nestjs/swagger';

import { appConfigFactory } from './app-config.factory';
import { AppModule } from './app.module';
// eslint-disable-next-line @typescript-eslint/ban-ts-comment -- The generated module is absent when type checking starts.
// @ts-ignore -- Generated by the Nest Swagger plugin during this build.
import metadata from './metadata';

async function bootstrap() {
  const app = await NestFactory.create(AppModule);
  const apiConfig = app.get<ConfigType<typeof appConfigFactory>>(appConfigFactory.KEY);

  if (apiConfig.corsOrigin) app.enableCors({ origin: apiConfig.corsOrigin });
  app.useGlobalPipes(new ValidationPipe({ transform: true, whitelist: true }));
  app.enableVersioning({ type: VersioningType.URI });
  // Starts listening for shutdown hooks
  app.enableShutdownHooks();

  if (apiConfig.documentationEnabled) {
    const config = new DocumentBuilder()
      .addBearerAuth({ in: 'header', type: 'http' })
      .setTitle('API Documentation')
      .setVersion('1.0.0')
      .build();
    await SwaggerModule.loadPluginMetadata(metadata);
    const document = SwaggerModule.createDocument(app, config);
    SwaggerModule.setup('documentation', app, document, {
      swaggerOptions: {
        operationsSorter: 'alpha',
        persistAuthorization: true,
        tagsSorter: 'alpha',
      },
    });
  }

  await app.listen(apiConfig.port ?? 3000);
}

bootstrap();
