name: api-format

on:
  pull_request:
    types: [opened, ready_for_review, reopened, synchronize]
    paths:
      - api/**
      - .github/**

jobs:
  api-format:
    name: api-format
    if: github.event_name != 'pull_request' || github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install dependencies
        uses: ./.github/actions/pnpm-install

      - name: Check format
        run: pnpm run format:check
